[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
solc = "0.8.28"

[rpc_endpoints]
educhain-testnet = "https://rpc.open-campus-codex.gelato.digital"

[etherscan]
educhain-testnet = { key = "XXX", url = "https://opencampus-codex.blockscout.com/api", chain = 656476 }

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.2.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
